### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by lubbertkramer** [duffbeer2000/deconz_fw_downloader#1]
When using your image on dockerhub https://hub.docker.com/r/duffbeer2000/deconz_fw_downloader i get the following error:

```
lkr@nuc-1701:~/docker$ docker-compose up -d --remove-orphans
Pulling deconz_fw_downloader (deconz_fw_downloader:latest)...
ERROR: The image for the service you're trying to recreate has been removed. 
If you continue, volume data could be lost. Consider backing up your data before 
continuing.

Continue with the new image? [yN] y
Pulling deconz_fw_downloader (deconz_fw_downloader:latest)...
ERROR: pull access denied for deconz_fw_downloader, repository does not exist 
or may require 'docker login': denied: requested access to the resource is denied
```

When pulling the image from youir get it results in:

```
lkr@nuc-1701:~/docker$ docker pull docker.pkg.github.com/duffbeer2000/deconz_fw_downloader
Using default tag: latest
Error response from daemon: 
Get https://docker.pkg.github.com/v2/duffbeer2000/deconz_fw_downloader/manifests/latest: no basic auth credentials
```

Edit and my docker compose:

```
  deconz_fw_downloader:
    container_name: deconz_fw_downloader
    image: deconz_fw_downloader:latest
    networks:
      - traefik
      #- frontend
      - backend
    volumes:
      - ${BASE}/deconz-fwdownloader:/config
      - ${BASE}/deconz-conbee/otau:/root/otau
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
```
